### ISSUE TITLE
mc parameter in import_xml() doesn't do anything

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#10]
The method seems to take a mc (I assume multicore?) parameter, but this parameter isn't passed to anything. Given how long it can take to import xmls, it certainly would be nice to have some kind of parallelization.

**Comment by ChristophLeonhardt** [comment]
Only tested quickly on rather large data, but this might be a solution:

      if (!all(file.exists(filenames))) stop("all files provided by x need to exist (not fulfilled)")
      if (is.null(mc) || mc == 1) {
        data <- if (progress) pblapply(filenames, .xml_reader) else lapply(filenames, .xml_reader) 
      } else {
        cl <- parallel::makeCluster(as.integer(mc), type = "FORK")
        data <- pblapply(filenames, .xml_reader, cl = cl)
        parallel::stopCluster(cl)
      }

Modifying the import_xml-function in CorpusData.R.

Not entirely sure if the makeCluster-Thing causes problems in the long run, i.e. if the clusters are stopped properly. Speeds up the process for the time being though.

**Comment by ablaette** [comment]
Good point, this is the modified suggestion of your code included now (dev version):

```r
if (is.null(mc) || mc == 1L){
  data <- pblapply(filenames, .xml_reader) else lapply(filenames, .xml_reader)
 } else {
   if (!is.numeric(mc))
   data <- if (progress)
     pblapply(filenames, .xml_reader, cl = mc)
   else
     mclapply(filenames, .xml_reader, mc.cores = mc)
}
```

This covers all combinations of the arguments `progress` and `mc`. Somewhat lazily, I omitted to create the cluster explicitly, and just used the `cl` argument of the `pbapply` function. But I am not sure that there is no difference.

Maybe you can check whether everything works as intended? I still find it somewhat difficult to write unit tests for parallelized code, because it is not portable to windows.
