### ISSUE TITLE
Missing line in the sentences vignette on dev-branch

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#17]
In the sentences vignette on the dev-branch (https://github.com/PolMine/cwbtools/blob/dev/vignettes/sentences.Rmd), one line is missing in the recipe: 

```
cpos <- seq.int(from = 0L, to = length(pos) - 1L)
```

should be included after 

```
pos <- corpus("GERMAPARL") %>% 
  get_token_stream(p_attribute = "pos")
```

otherwise the split won't work afterwards.

**Comment by ablaette** [comment]
Many thanks for pointing out the issue and for offering a solution. Admittedly, the vignette was a draft rather than ready. The error you report should not have gone unnoticed ... Anyway, I reworked the code in the vignette so that it is a working example, I will push it right away to the dev branch.
