### ISSUE TITLE
corpus_as_tarball doesn't work if working directory is home

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#9]
If working directory is "~/"

Error in setwd(old_wd) : character argument expected

**Comment by ablaette** [comment]
My first assumption was that this is an issue with abbreviated file names, and a turned the line you referred to (`setwd(old_wd)`) into `setwd(path.expand(old_wd))`, so that tilde expansion is performed.

However, I am not sure whether this is really the point, because this is not a problem:

```r
setwd("~")
p <- setwd("~/Lab")
setwd(p)
```

Maybe you can offer a full reproducible example to be able to get behind what might be wrong.

**Comment by ablaette** [comment]
The function uses a temporary directory and the issue is gone.
